export type Language = 'en' | 'hi';

export const translations = {
    en: {
        // Navigation
        nav: {
            dashboard: "Dashboard",
            journal: "Journal",
            talk: "Talk",
            insights: "Insights",
            settings: "Settings",
            menu: "Menu",
            logout: "Log out",
        },
        // Dashboard
        dashboard: {
            greeting: "Hello",
            welcome: "Welcome back",
            dailyQuote: "Your feelings are valid.",
            newEntry: "New Entry",
            recentEntries: "Recent Entries",
            noEntries: "No entries yet. Start writing!",
            viewAll: "View All",
        },
        // Journal
        journal: {
            title: "My Journal",
            subtitle: "Capture your thoughts and feelings.",
            writePlaceholder: "Write about your day...",
            saved: "Saved",
            saving: "Saving...",
            analyze: "Analyze Emotion",
            analyzing: "Analyzing...",
            moodScore: "Mood Score",
            emotions: "Emotions",
            delete: "Delete",
        },
        // Talk
        talk: {
            title: "Voice Chat",
            subtitle: "Speak your mind freely.",
            listening: "Listening...",
            speaking: "Speaking...",
            processing: "Thinking...",
            tapToSpeak: "Tap to speak",
            tapToStop: "Tap to stop",
            send: "Send",
        },
        // Insights
        // Insights
        insights: {
            title: "Insights",
            subtitle: "Discover patterns in your emotional well-being using AI.",
            moodTrends: "Mood Trends (Last 30 Days)",
            topEmotions: "Top Emotions",
            analyzing: "Analyzing your journey...",
            noMoodData: "No mood data available yet.",
            noEmotions: "No emotions logged yet.",
            aiTitle: "AI Companion Insights",
            noInsights: "Gathering enough journal entries to generate meaningful insights...",
            aiFooter: "Generated by analyzing your recent entries securely.",
        },
        // Common
        common: {
            loading: "Loading...",
            error: "Something went wrong.",
            success: "Success",
            retry: "Retry",
        }
    },
    hi: {
        // Navigation
        nav: {
            dashboard: "डैशबोर्ड",
            journal: "पत्रिका",
            talk: "बातचीत",
            insights: "अंतर्दृष्टि",
            settings: "सेटिंग्स",
            menu: "मेनू",
            logout: "लॉग आउट",
        },
        // Dashboard
        dashboard: {
            greeting: "नमस्ते",
            welcome: "वापसी पर स्वागत है",
            dailyQuote: "आपकी भावनाएं मान्य हैं।",
            newEntry: "नई प्रविष्टि",
            recentEntries: "हाल की प्रविष्टियां",
            noEntries: "अभी तक कोई प्रविष्टि नहीं। लिखना शुरू करें!",
            viewAll: "सभी देखें",
        },
        // Journal
        journal: {
            title: "मेरी पत्रिका",
            subtitle: "अपने विचारों और भावनाओं को कैद करें।",
            writePlaceholder: "अपने दिन के बारे में लिखें...",
            saved: "सहेजा गया",
            saving: "सहेज रहा है...",
            analyze: "भावना का विश्लेषण करें",
            analyzing: "विश्लेषण कर रहा है...",
            moodScore: "मनोदशा स्कोर",
            emotions: "भावनाएं",
            delete: "हटाएं",
        },
        // Talk
        talk: {
            title: "वॉयस चैट",
            subtitle: "खुलकर अपने मन की बात कहें।",
            listening: "सुन रहा हूँ...",
            speaking: "बोल रहा हूँ...",
            processing: "सोच रहा हूँ...",
            tapToSpeak: "बोलने के लिए टैप करें",
            tapToStop: "रोकने के लिए टैप करें",
            send: "भेजें",
        },
        // Insights
        insights: {
            title: "अंतर्दृष्टि",
            subtitle: "एआई का उपयोग करके अपनी भावनात्मक भलाई में पैटर्न खोजें।",
            moodTrends: "मनोदशा के रुझान (पिछले 30 दिन)",
            topEmotions: "शीर्ष भावनाएं",
            analyzing: "आपकी यात्रा का विश्लेषण कर रहा है...",
            noMoodData: "अभी तक कोई मनोदशा डेटा उपलब्ध नहीं है।",
            noEmotions: "अभी तक कोई भावनाएं दर्ज नहीं की गई हैं।",
            aiTitle: "एआई साथी की अंतर्दृष्टि",
            noInsights: "सार्थक अंतर्दृष्टि उत्पन्न करने के लिए पर्याप्त पत्रिका प्रविष्टियां एकत्रित कर रहा है...",
            aiFooter: "आपकी हाल की प्रविष्टियों का सुरक्षित रूप से विश्लेषण करके उत्पन्न किया गया।",
        },
        // Common
        common: {
            loading: "लोड हो रहा है...",
            error: "कुछ गलत हो गया।",
            success: "सफल",
            retry: "पुनः प्रयास करें",
        }
    }
};
